[package]
name = "bevy_defer"
version = "0.3.2"
edition = "2021"

authors = ["Mincong Lu <mintlux667@gmail.com>"]
license = "MIT OR Apache-2.0"

readme = "README.md"
repository = "https://github.com/mintlu8/bevy_defer"
description = """
A simple asynchronous runtime for executing deferred queries.
"""
keywords = ["bevy", "async", "defer"]

[lib]
doctest = false

[dependencies]
triomphe = "^0.1.11"
parking_lot = "^0.12"
once_cell = "^1.19"
thiserror = "^1"
downcast-rs = "^1.2"
async-channel = "2.2.0"
ref-cast = "1.0.22"
bevy_ecs = "0.13.0"
bevy_hierarchy = "0.13.0"
bevy_app = "0.13.0"
bevy_animation = "0.13.0"
bevy_asset = "0.13.0"
bevy_reflect = "0.13.0"
bevy_log = "0.13.0"
bevy_tasks = "0.13.0"
bevy_time = "0.13.0"
rustc-hash = "1.1.0"
scoped-tls = "1.0.1"
futures = "0.3.30"

[dev-dependencies]
bevy = { version = "0.13.0", default-features = false, features = ["multi-threaded"] }
