[workspace] 
members = [ 
    "http"
]

[package]
name = "bevy_defer"
version = "0.9.0"
edition = "2021"

authors = ["Mincong Lu <mintlux667@gmail.com>"]
license = "MIT OR Apache-2.0"

readme = "README.md"
repository = "https://github.com/mintlu8/bevy_defer"
description = """
A simple asynchronous runtime for executing async coroutines.
"""
keywords = ["bevy", "async", "defer"]

[features]
default = ["bevy_ui", "bevy_animation", "bevy_mod_picking"]
bevy_mod_picking = ["dep:bevy_mod_picking"]

[dependencies]
futures = { version = "0.3.30", default-features = false }
async-executor = "1.10.0"

parking_lot = "0.12"
once_cell = "1.19"
thiserror = "1"
downcast-rs = "1.2"
ref-cast = "1.0.22"
bevy_ecs = "0.13.1"
bevy_hierarchy = "0.13.1"
bevy_app = "0.13.1"
bevy_asset = "0.13.1"
bevy_reflect = "0.13.1"
bevy_log = "0.13.1"
bevy_tasks = "0.13.1"
bevy_time = "0.13.1"
bevy_math = "0.13.1"
bevy_core = "0.13.1"
bevy_utils = "0.13.1"
rustc-hash = "1.1.0"
scoped-tls = "1.0.1"

bevy_animation = { version = "0.13.1", optional = true }
bevy_ui = { version = "0.13.1", optional = true }
bevy_mod_picking = { version = "0.18.2", optional = true, default-features = false, features = ["selection"] }

[dev-dependencies]
bevy = { version = "0.13.0" }
bevy_mod_picking = { version = "0.18.2" }
futures = { version = "0.3.30" }
